### ISSUE TITLE
Reinstate MARINe rocky intertidal modals

### ISSUE THREAD

**Issue by bbest** [noaa-onms/ocnms#18]
- [x] package install issues
- [ ] Can't parse `date` column

These must've gotten dropped when I auto-generated the modals.

Reinstate the MARINe rocky intertidal datasets using `onmsR` functions under [Reference - Data: Rocky intertidal (MARINe) | onmsR](https://noaa-onms.github.io/onmsR/reference/index.html#section-data-rocky-intertidal-marine-) and looking at previous versions of the files from commit history.

**Comment by bbest** [comment]
## DONE: Barnacles

Got the basics to work for barnacles in these commits:
* [fix _site.yml to output_dir: "." vs "_site"; only barnacles for now · noaa-onms/ocnms@a5524ed](https://github.com/noaa-onms/ocnms/commit/a5524ed73a3dd80e017cc5202a7186b65587afb2)
* [+ rocky-shore_barnacles dynamic again · noaa-onms/ocnms@2ae308f](https://github.com/noaa-onms/ocnms/commit/2ae308f6fae847caf3fc98447e722fdf68ad72bb)
![image.png](https://images.zenhubusercontent.com/53c976bbe6799ebe48001049/41b4f020-0b15-49c7-abc0-5ac2b76ac059)

And new dynamic_modal` column (`T` or `F`) in [Master_OCNMS_infographic_content - Google Sheets](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit?pli=1#gid=1778111652) for modals.

## TODO: other dynamic Rmds from previous MARINe modals
- Download zip from previous version from https://github.com/noaa-onms/ocnms/tree/ac87c3396cf50c87b099588218f6b9785df58589:
  ![image.png](https://images.zenhubusercontent.com/53c976bbe6799ebe48001049/a063f190-aa1b-420b-aa32-d0b9a42e6c5b)
- Mix dynamic from there into the static from latest and set flag `T` in `dynamic_modal` column of [Master_OCNMS_infographic_content - Google Sheets](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit?pli=1#gid=1778111652)

**Comment by mspector13** [comment]
Hey @bbest 

I was finally able to update 

`rocky-shore_ochre-star.Rmd` 
`rocky-shore_mussels.Rmd` 

They should have interactive plots and maps as well as the static images *not* derived from 'data/rocky-intertidal_MARINe/sanctuary_species_percentcover.csv"' (I.e, **Trends - condition** `r insert_figure("rocky-shore_mussels.html", "figures/S.LR.12.5 - Mussell shell thickness.jpg")`). I changed the status in the new dynamic_modal column  in Master_OCNMS_infographic_content - Google Sheets for modals to reflect this.

I also went ahead and added a dynamic graph of Dwarf Rockweed to a **new** file `rocky-shore_macroalgae-surfgrass_dynamic.Rmd`. The current version (`rocky-shore_macroalgae-surfgrass.Rmd`) called in the WebCR has a static MARINe plot, *not* a screenshot of a dynamic plot. However, there are dynamic plots in the pervious version of this modal window. We can keep it as is, or call the new `.Rmd` file. 

From what I can tell, these are the only other interactive plots that needed to be added back in. 

Unfortunately, I am unable to knit any of these files on my end. ~~Based on the screenshot below, I cannot  seem to load the `onmsR` package based on my current version of R.~~ I am confused by this error message:

![Screen Shot 2021-11-19 at 2 41 06 PM](https://user-images.githubusercontent.com/59982410/142700470-63fb9b4b-210a-4e4f-b2b7-c67cfcf5ee06.png)

The path in `infographiqR.R` for my user access is still correct. The repo is also up to date; any thoughts?

**Comment by mspector13** [comment]
**Resolved** 

Revisiting thing. We should have interactive plots for Mussels and `rocky-shore_mussels.Rmd` and `rocky-shore_ochre-star.Rmd`. 

This call should be working

<img width="713" alt="Screen Shot 2022-01-06 at 4 51 58 PM" src="https://user-images.githubusercontent.com/59982410/148473564-c73a9dbb-e29d-4b31-812d-d6d18cf5c65b.png">

But it's erroring out: 
<img width="611" alt="Screen Shot 2022-01-06 at 4 49 10 PM" src="https://user-images.githubusercontent.com/59982410/148473366-4f8f0ef6-2e1b-47be-a9b6-1446d0ba454f.png">

Something in `plot_intertidal_nms()` isn't working, the file is called `sanctuary_species_sscount.csv`. Need to change this in `onmsR`

TODO: Download latest and greatest MARINe data ASAP

**Comment by mspector13** [comment]
Current issue:

- [x] Need to add captions to dynamic figures. Specifically, need to add _something_ to `insert_figure()` to correctly call captions from [master-spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539).

Example for *non-dynamic* figures:
![Screen Shot 2022-01-12 at 11 23 42 AM](https://user-images.githubusercontent.com/59982410/149207846-0d425e4b-c4de-4505-a94c-4ed0a37243a1.png)

This errors out for dynamic figures:
![Screen Shot 2022-01-12 at 11 26 34 AM](https://user-images.githubusercontent.com/59982410/149208260-f714af0c-29ac-42d8-a406-14109c3d1898.png)

![Screen Shot 2022-01-12 at 11 25 27 AM](https://user-images.githubusercontent.com/59982410/149208100-ee438e9a-eb0d-4769-a38f-7d47cee08226.png)


- [ ] Need to change the default plotting for the way dygraphs addresses axis ticks: [dygraphs x-axis labels ](https://rstudio.github.io/dygraphs/gallery-axis-options.html). Currently, dygraphs defaults to printing "Jan" on axis ticks for time series data. We can likely change this, but it's going to take some serious sleuthing

**Comment by mspector13** [comment]
Update: there are other modals that might have a caption, but no text (e.g., `kelp-forest_benthic-intertebrates.Rmd`). `insert_figure()` needs arguments for both figures *and* captions. What do?

**Comment by mspector13** [comment]
Update: the updated MARINe data are now in `./data/rocky-intertidal_MARINe` and labeled accordingly (with "_new" as the suffix). Everything *should* be formatted correctly. However, something isn't working right:
![Screen Shot 2022-01-14 at 1 21 37 PM](https://user-images.githubusercontent.com/59982410/149587050-3b7b4480-1f8b-433a-a613-5f18238daf4d.png)

w/ backtrace: 
![Screen Shot 2022-01-14 at 1 21 08 PM](https://user-images.githubusercontent.com/59982410/149587081-6cfb6f7d-d2e9-47f1-8b70-508d1f7f5a59.png)

**Comment by bbest** [comment]
`modals/rocky-shore_barnacles.Rmd`
