### ISSUE TITLE
TODO: Modals to fix

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#31]
These are the modals that need tweaking/fixing/work. 

Reference and more details: Jai's  [OCNMS Modal Window Problems](https://docs.google.com/spreadsheets/d/1CI7lxXOcA7uvKCpzNez-nu97EF1AIXtnVfKkdzCp0G8/edit#gid=0) spreadsheet

- [x] Deep Seafloor | NIS `insert_caption()`
- [x] Deep seafloor | Corals and Sponges `insert_caption()`
- [x] Deep seafloor | Green Sturgeon `insert_caption()`
- [x] ~~Deep Seafloor | Seafloor terrain complexity~~
- [x] ~~Deep Seafloor | Shad~~
- [x] Kelp Forest | Benthic Invertebrates `insert_caption()`
- [x] Kelp Forest | Kelp canopy
- [x]  Kelp Forest | Understory Algae `insert_caption()`
- [x] Pelagic | Forage fish
- [x] Pelagic | Humboldt Squidt `insert_caption()`
- [x] Pelagic | Leatherback
- [x] Pelagic | Midwater Rockfishes `insert_caption()`
- [x] Pelagic | Larvae and zooplankton: Maps - Larvae and zooplankton stations
- [x] Pelagic | Larvae and zooplankton: Maps - Phytoplankton
- [x] Rocky Shore | Algae and surfgrass: Trends - Rockweed
- [x] Rocky Shore | Black Oystercatcher `insert_caption()`
- [x] Rocky Shore | Invertebrate Diversity `insert_caption()` 
- [ ] Rocky Shore | Barnacles
- [ ] Rocky Shore | Mussels
- [ ] Rocky Shore | Ochre stars: Trends and Condition
- [x] ~~Beaches | Amphipods and isopods~~
- [x] Beaches | Beach wrack `insert_caption()`
- [x] ~~Beaches | Decapods~~
- [x] ~~Beaches | Beach Sediment~~
- [x] ~~Beaches | Infaunal Predators~~
- [x] ~~Beaches | Position Slope~~
- [x] ~~Beaches | Olive snails~~
- [x] ~~Beaches | Phytoplankton~~
- [x] ~~Beaches | Pinnipeds~~
- [x] ~~Beaches | Shorebirds~~
- [x] Beaches | Surfzone fish `insert_caption()`
- [x] ~~Sandy seafloor | Benthic invertebrates~~
- [x] Sandy seafloor | Forage fish
- [x] Sandy Seafloor | Flatfishes `insert_caption()`
- [x] Ocean and climate | Dissolved oxygen Map - DO and halibut 2017
- [x] Ocean and climate | Dissolved oxygen Trends - Near-Bottom DO
- [x] Ocean and climate | Ocean acidification Trends - Benthic Aragonite Saturation
- [x] Ocean and climate | Ocean acidification Trends - Benthic pH
- [x] Ocean and climate | Physical processes `insert_caption()`
- [x] Ocean and climate | Water chemistry `insert_caption()`
- [x] Human connections | Aquaculture
- [ ] Human connections | Education and engagement
- [x] ~~Human connections | Energy~~
- [x] Human connections | Harvest Fishing, personal use
- [x] Human connections | Harvest Trends - Dungeness crab catch, revenue
- [x] Human connections | Harvest Trends - Halibut biomass
- [x] Human connections | Harvest Trends - Revenue, salmon troll
- [x] Human connections | Harvest  Trends - Vessels, salmon troll fleet
- [x] Human connections | Harvest Trends - whiting catch
- [x] Human connections | Military activity
- [x] Human connections | Non-consumptive recreation Map - Recreational activities 
- [ ] Human connections | Science: community science activities
- [ ] Human connections | Science: trends R/V Tatoosh
- [x] Human connections | Sense of place `insert_caption()`
- [x] Human connections | Spills and discharges Map - Petroleum movement
- [x] Human connections | Spills and discharges Map - Tenyo Maru oil spill
- [x] Human connections | Spills and discharges Trends - Petroleum movement
- [x] Human connections | Vessels Map - Vessel density
- [x] Human connections | Vessels Trends - Cruise passengers 
- [x] Human connections | Wildlife disturbance: Map - Entangled Whales

**Comment by mspector13** [comment]
Hey guys, 

Just a heads up that I added `insert_caption()` to the items on the checklist to note which modals need to have captions without images. To avoid override issues I set `dynamic` to **T** in the [master spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) for these modals. E.g.:
<img width="679" alt="Screen Shot 2022-02-14 at 3 12 40 PM" src="https://user-images.githubusercontent.com/59982410/153962522-0adfc4f3-0038-420e-b426-24a799049d77.png">


Also, ~~strikethroughs~~ mean the modal is no longer included in the [WebCR](https://noaa-onms.github.io/ocnms). 

All of the modals above either have [text wrapping issues ](https://github.com/noaa-onms/ocnms/issues/23) or are dynamic figures (e.g. Issues #32)

**Comment by mspector13** [comment]
Updated all of the images that needed to be resized. Images were downloaded from the [master spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539), edited in gimp, and then uploaded to a [*new* folder](https://drive.google.com/drive/u/1/folders/1h5LmQ6hlma3xGZTFEq6P1_utsF2Fd16V). 
`image_link` urls have been updated for said images, everything **should** be working now!

**Comment by mspector13** [comment]
Closing this issuer (for now at least).

Issue #39 and #38 both capture outstanding issues
